#! /bin/bash


echo -n "directory path> "
read dir

echo "Total size of disk"
sudo du -sh $dir

echo "Disk's device path"

cd $dir
pwd

echo "Mounted on"
df -P $dir | tail -1 | cut -d'%' -f 2


echo "Partition's size"
cd $dir
du -h $dir

echo "Usage"
cd $dir
df -h $dir

echo "Number of directories"
cd $dir
ls -l | grep ^d | wc -l

echo "Number of files"
find $dir -type f | wc -l

# find file with longest filename

longestname=0

for file in $dir/*; do
    file=`echo $file | sed s,$dir/,,`
    sz=`echo $file | wc -c`             # get filename length
    if [ $sz -gt $longestname ]; then
        longestname=`expr $sz - 1`      # reduce by 1 for carriage return
        longname=$file
    fi
done

echo $longestname:  $longname

echo "Files suid or sticky setted:"
find $dir -perm -4000 -print
find $dir -perm -1000 -print

exit
