#! /bin/bash


# Disk toplam boyutu
echo -n "dir> "
read dir

sudo du -sh $dir/,,

# Disk's device path

cd $dir/,,
pwd

# Mounted on
df -P $dir/,, | tail -1 | cut -d'/' -f 2

# Partition's size
cd $dir/,,
du -h $dir/,,

# Usage
cd $dir/,,
du -ah $dir/,,

# Number of directories
cd $dir/,,
ls -l | grep ^d | wc -l

# Number of files
find $dir/,, -type f | wc -l

# find file with longest filename
echo -n "dir> "
read dir
longestname=0

for file in $dir/*; do
    file=`echo $file | sed s,$dir/,,`
    sz=`echo $file | wc -c`             # get filename length
    if [ $sz -gt $longestname ]; then
        longestname=`expr $sz - 1`      # reduce by 1 for carriage return
        longname=$file
    fi
done

echo $longestname:  $longname

# find files setted suid & sticky
find $dir/,, -perm -4000 -print
find $dir/,, -perm -1000 -print

exit
